version: '3'
services:
    backend:
        container_name: notice
        build:
            dockerfile: Dockerfile
            context: .
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - ${PORT}:8000
