export const config = {
  PORT: process.env.PORT,
  MONGODB_CONNECTION_URL: process.env.MONGODB_CONNECTION_URL,
  FACEBOOK_API_BASE_URL: process.env.FACEBOOK_API_BASE_URL,
  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
  BITLY_ACCESS_TOKEN: process.env.BITLY_ACCESS_TOKEN,
  BITLY_API_URL: process.env.BITLY_API_URL,
  WEBSITE_URL: process.env.WEBSITE_URL,
};
